name: Automated Data Preprocessing

on:
  push:
    paths:
      - 'preprocessing/automate_Mohammad-Aris-Darmawan.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn kagglehub

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Mohammad-Aris-Darmawan.py

    - name: Commit and Push Preprocessed Data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Tarik data terbaru dari server SEBELUM melakukan commit
        git pull origin main --rebase
        
        git add preprocessing/hotel_bookings_preprocessed.csv
        git commit -m "Auto-update: Generate dataset preprocessed terbaru via Kaggle API" || echo "Tidak ada perubahan data"
        
        # Paksa push ke branch main
        git push origin main